openai_key = "lll"
openai_base_url = "http://localhost:1234/v1"
model_name = "lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF"
embedding_model_name="local:BAAI/bge-small-en-v1.5"
provider = "lm_studio"